In [2]:
import glob
import os
import pickle as pkl
import re
import sys

from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from tqdm import tqdm

In [3]:
with open('../../datasets/oqmd_dataset.pkl', "rb") as f:
    oqmd_db = pkl.load(f)

In [6]:
oqmd_useful = oqmd_db.dropna(axis=1)
oqmd_useful

,name,entry_id,composition_generic,spacegroup,volume,ntypes,natoms,delta_e,stability
0,DyRuO3,1730890,ABC3,I4/mcm,116.984,3,10,-2.209178,0.286549
1,DyScO3,1730891,ABC3,I4/mcm,121.878,3,10,-3.600806,0.227905
2,DyVO3,1730892,ABC3,I4/mcm,112.458,3,10,-3.084564,0.185952
3,DyZrO3,1730893,ABC3,I4/mcm,130.633,3,10,-3.188064,0.381106
4,ErLuO3,1730894,ABC3,I4/mcm,132.569,3,10,-3.501097,0.428042
...,...,...,...,...,...,...,...,...,...
23107,MgRuO3,1738575,ABC3,Cmc21,148.688,3,10,-1.595464,0.343998
23108,MgTiO3,1738576,ABC3,Cmc21,141.714,3,10,-3.146054,0.042145
23109,CeLuSe3,1739101,ABC3,C2221,267.084,3,10,-1.888413,0.000000
23110,NdSeO3,1739235,ABC3,P21/m,134.123,3,10,-2.128477,0.110636
23111,PdPbO3,1739236,ABC3,P21/m,134.204,3,10,-0.726272,0.221704

In [8]:
with open("oqmd_ids.pkl", "wb") as wf:
    pkl.dump(oqmd_useful["entry_id"], wf)

In [ ]:
oqmd_useful["name"].str.